# https://travis-ci.com/tczorro/SpSaddle
language: python
python:
    - 2.7
    - 3.5

install:
    - pip install -r requirements.txt
    - pip install pylint
    - pip install pycodestyle
    - python setup.py install

script:
    - nosetests --with-coverage --cover-package=fitting -v ./fitting/
    - pylint saddle --errors-only
    - pycodestyle ./fitting/ --max-line-length=100

notifications:
  email: false
