language: python
python:
    - 2.7
    - 3.5

install:
    - pip install numpy scipy nose matplotlib
    - pip install pylint
    - pip install pycodestyle pydocstyle

script:
    - nosetests --with-coverage --cover-package=fitting -v ./fitting/
    - pylint ./fitting/ --errors-only
    - pycodestyle ./fitting/ --max-line-length=100
    - pydocstyle ./fitting/

notifications:
  email: false
